name: Unit Tests

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths-ignore:
      - "**.md"

jobs:
  tests-ubuntu:
    name: Unit Tests (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Test (SH)
        run: ACTUAL_SHELL="sh" cargo test
        shell: sh
      - name: Test (BASH)
        run: ACTUAL_SHELL="bash" cargo test
        shell: bash
      - name: Test (ZSH)
        run: ACTUAL_SHELL="zsh" cargo test
        shell: zsh
  tests-macos:
    name: Unit Tests (MacOS)
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Test (SH)
        run: ACTUAL_SHELL="sh" cargo test
        shell: sh
      - name: Test (BASH)
        run: ACTUAL_SHELL="bash" cargo test
        shell: bash
      - name: Test (ZSH)
        run: ACTUAL_SHELL="zsh" cargo test
        shell: zsh
  tests-windows:
    name: Unit Tests (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Test (PowerShell)
        run: ACTUAL_SHELL="powershell" cargo test
        shell: powershell
      - name: Test (CMD)
        run: ACTUAL_SHELL="cmd" cargo test
        shell: cmd
